services:
  feed-api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    container_name: feed-api
    restart: unless-stopped
    ports:
      - "4001:4001"
    env_file:
      - .env
    environment:
      MONGO_URI: ${MONGO_URI}

  mongo:
    image: mongo:latest
    container_name: feed-mongo-db
    restart: unless-stopped
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "127.0.0.1:27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
